aligned images to center
publiclab/infragram pull request #266
Opened 2022-03-30 07:36 UTC by shubhangi013

solved #265 
![Screenshot from 2022-03-30 13-05-13](https://user-images.githubusercontent.com/78342516/160777125-8aa21e4b-eeb0-4d14-ae29-e6e233f1b6b5.png)

2022-03-30 23:09 UTC, TildaDares requested changes

2022-03-31 02:06 UTC, shubhangi013 commented
@TildaDares I've done the requested changes :smile:

2022-03-31 06:52 UTC, TildaDares requested changes

2022-03-31 06:52 UTC, TildaDares commented on README.md
> +</div>
@shubhangi013 The alt text is the text between the square brackets.

2022-03-31 06:52 UTC, TildaDares commented on README.md
> +</div>
Look at line 16 of the code you removed.

2022-03-31 11:40 UTC, shubhangi013 commented
@TildaDares you can check now. :smile:

2022-04-04 13:58 UTC, TildaDares requested changes

2022-04-04 13:58 UTC, TildaDares commented on README.md
> +<img src='https://publiclab.org/system/images/photos/000/045/470/medium/Screen_Shot_2022-03-08_at_2.56.38_PM.png' alt='colorizing example'>
```suggestion
<img src='https://publiclab.org/system/images/photos/000/045/470/medium/Screen_Shot_2022-03-08_at_2.56.38_PM.png' alt='screenshot of the color bar'>
```

2022-04-04 14:08 UTC, shubhangi013 commented
@TildaDares I've done the suggested changes!

2022-04-04 14:16 UTC, TildaDares approved these changes
Great work @shubhangi013!!

2022-04-04 14:16 UTC, merged