Create PULL_REQUEST_TEMPLATE.md
publiclab/infragram pull request #364
Opened 2022-04-12 18:10 UTC by adeolaadedeji

Created a pull request file/Template

2022-04-12 18:46 UTC, on2onyekachi commented
Awesome! @adeolaadedeji 

You'll need to site the issue number associated with this PR.

2022-04-12 19:03 UTC, adeolaadedeji commented
Thank you @on2onyekachi for the feedback, i have  stated the issue assigned to me.

2022-04-12 19:03 UTC, adeolaadedeji commented
Thank you @on2onyekachi for the feedback, i have  stated the issue assigned to me.

2022-04-12 19:22 UTC, on2onyekachi commented
oh Sorry, @adeolaadedeji.  Not in the General chat.  you need to state it in the description of this PR.

2022-04-12 19:25 UTC, adeolaadedeji commented
Okay @on2onyekachi , thanks. This was the fto assigned to me.......[publiclab/infragram#363](https://github.com/publiclab/infragram/issues/363)

2022-04-12 19:34 UTC, on2onyekachi commented
Okay @adeolaadedeji 

> Okay @on2onyekachi , thanks. This was the fto assigned to me.......[publiclab/infragram#363](https://github.com/publiclab/infragram/issues/363)

 Great!, now you need to make an edit and add just the issue number only to the description of your PR. It should be in the format `fixes #0000.` Where #0000 is the issue number.

2022-04-12 19:40 UTC, adeolaadedeji commented
Hi @on2onyekachi , this has been worked on. kindly review

2022-04-12 19:55 UTC, on2onyekachi commented
@adeolaadedeji I think you made a change to the file itself. Please revert those changes. I dropped you a private message on how to edit the description itself.

2022-04-12 20:05 UTC, adeolaadedeji commented
Thank you for the guidelines @on2onyekachi, i have worked on it. Can you please check it now?

2022-04-12 20:11 UTC, on2onyekachi commented
@adeolaadedeji Yeah, this is better! now. it shows a commit message that references the raised issue pointing to this PR.

2022-04-12 20:14 UTC, adeolaadedeji commented
@on2onyekachi , thank you lots..

2022-04-13 06:26 UTC, TildaDares requested changes
@adeolaadedeji You need to copy the markdown and not just the text. Can you copy the contents of this file https://github.com/publiclab/plots2/edit/main/.github/PULL_REQUEST_TEMPLATE.md and paste again? Thanks!!

2022-04-13 08:31 UTC, adeolaadedeji commented
Thank you @TildaDares , i have worked it. Kindly review

2022-04-13 17:38 UTC, TildaDares requested changes
Hi @adeolaadedeji, can you make that small correction? Thanks!!

2022-04-13 17:38 UTC, TildaDares commented on .github/PULL_REQUEST_TEMPLATE.md
> +* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
```suggestion
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR

2022-04-13 18:16 UTC, adeolaadedeji commented
Hi @TildaDares , changes effected, kindly review. Thank you.

2022-04-13 18:26 UTC, TildaDares approved these changes
Thanks @adeolaadedeji. Great work!!

2022-04-13 18:26 UTC, merged

2022-04-13 18:27 UTC, TildaDares commented
Congratulations @adeolaadedeji 🎉

2022-04-13 18:59 UTC, adeolaadedeji commented
Thank you so much @TildaDares .